apiVersion: v1
kind: Service
metadata:
  name: blue-web-np
  namespace: default
spec:
  selector:
    app: blue-web  
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
