apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: k8auth
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet: 
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5    
          timeoutSeconds: 5
          failureThreshold: 1
